// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh-access": {
            "post": {
                "description": "Принимает refreshToken и возвращает новый accessToken БЕЗ изменения сессии рефреша. Доступен без авторизации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление Access токена",
                "parameters": [
                    {
                        "description": "Действующий Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RefreshJwtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новый access токен",
                        "schema": {
                            "$ref": "#/definitions/domain.JwtResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный формат JSON",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или просроченный токен",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Принимает refreshToken, инвалидирует его и возвращает полностью новую пару Access и Refresh токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Полное обновление пары токенов (Ротация)",
                "parameters": [
                    {
                        "description": "Действующий Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RefreshJwtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новая пара токенов",
                        "schema": {
                            "$ref": "#/definitions/domain.JwtResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный формат JSON",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или просроченный токен",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "description": "Проверяет учетные данные пользователя (логин/пароль) и возвращает пару JWT токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя (Вход)",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.JwtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход, возвращает токены",
                        "schema": {
                            "$ref": "#/definitions/domain.JwtResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный формат JSON",
                        "schema": {
                            "$ref": "#/definitions/domain.JwtResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный логин или пароль",
                        "schema": {
                            "$ref": "#/definitions/domain.JwtResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Создает новый аккаунт и сразу возвращает JWT-токены для авторизации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации (логин и пароль)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса (невалидный JSON)",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "422": {
                        "description": "Ошибка бизнес-валидации (пользователь уже существует, слишком короткий пароль)",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    }
                }
            }
        },
        "/game": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Инициализирует новую игру 3х3 с выбором оппонента (ИИ или человек). Требует авторизацию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Создание новой игровой комнаты",
                "parameters": [
                    {
                        "description": "Принимает строку ai или human",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат тела запроса или невалидный opponent_type",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при сохранении в БД",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/game/{current_game_UUID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает текущее состояние игровой сессии (доску, статус, ID игроков) по её UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получение информации о конкретной игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID игровой сессии",
                        "name": "current_game_UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Игровая сессия не найдена",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Принимает новое состояние игрового поля от авторизованного пользователя.\nПроверяет очередность хода, валидирует корректность изменения клеток.\nЕсли оппонент — ИИ, то сервер автоматически рассчитывает и совершает ответный ход.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Совершение хода в игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID игровой сессии",
                        "name": "current_game_UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новое состояние игрового поля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ход успешно принят (и выполнен ответный ход ИИ, если применимо)",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID, сломанный JSON, игра окончена или еще не началась",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Ход не в свою очередь или пользователь не является участником этой игры",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Игровая сессия не найдена в базе данных",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации доски (изменено более 1 клетки, затерты чужие фигуры)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при расчетах ИИ или сохранении в БД",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/game/{current_game_UUID}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Позволяет авторизованному пользователю занять свободное место (Нолика) в комнате со статусом ожидания.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Присоединение к существующей игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID игровой сессии",
                        "name": "current_game_UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное подключение, статус игры изменен на PlayerXTurn",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID или бизнес-ошибка (комната заполнена, попытка войти в свою комнату)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/available": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех созданных игровых комнат, находящихся в статусе ожидания второго игрока (WaitingForPlayers).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получение списка доступных игр",
                "responses": {
                    "200": {
                        "description": "Список доступных комнат (может быть пустым [])",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.GameResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при запросе к БД",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех завершенных игр (победа, поражение, ничья), в которых участвовал текущий пользователь. Требует авторизацию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получение истории завершенных игр пользователя",
                "responses": {
                    "200": {
                        "description": "Список завершенных игр",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.GameResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при чтении из БД",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает топ N игроков с наилучшим соотношением побед к поражениям и ничьим.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получение таблицы лидеров",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество игроков в выборке (по умолчанию 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LiederBoard"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректное значение параметра limit",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает профиль пользователя, извлекая UUID из проверенного accessToken в заголовке Authorization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации о текущем пользователе",
                "responses": {
                    "200": {
                        "description": "Данные профиля авторизованного пользователя",
                        "schema": {
                            "$ref": "#/definitions/api.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Токен отсутствует, невалиден или просрочен",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь с таким UUID не найден в БД",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает публичный профиль пользователя (ID и логин) по его UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации о пользователе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя",
                        "name": "user_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.CreateGameRequest": {
            "type": "object",
            "properties": {
                "opponent_type": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.GameRequest": {
            "type": "object",
            "properties": {
                "board": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "api.GameResponse": {
            "type": "object",
            "properties": {
                "board": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "game_status": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "player_o_id": {
                    "type": "string"
                },
                "player_x_id": {
                    "type": "string"
                }
            }
        },
        "api.SignUpRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.UserResponse": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.JwtRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.JwtResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "type": {
                    "description": "Обычно \"Bearer\"",
                    "type": "string"
                }
            }
        },
        "domain.LiederBoard": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "win_rate": {
                    "type": "number"
                }
            }
        },
        "domain.RefreshJwtRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer {accessToken}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
